### ISSUE TITLE
emblem now has handlebars version dependencies ...

### ISSUE THREAD

**Issue by breathe** [dbashford/mimosa#247]
Emblem [https://github.com/machty/emblem.js] apparently has compatibility with only specific handlebars versions now ...  handlebars in turn is compatible with only specific ember's ...

I can specify the handlebars version to use for pre-compiling like so -- this allows me to specify a handlebars compatible with my project's ember:

```
    handlebars:
      lib: require('handlebars')
      helpers:["app/handlebars-helpers"]
      ember:
        enabled: true
```

Would it be feasible to be able to specify the emblem pre-compiler version via a similar mechanism (so I could specify a emblem version compatible with my projects handlebars ...) ...?

```
    emblem:
      lib: require('emblem')
```
