### ISSUE TITLE
shim paths can reference 'path' paths

### ISSUE THREAD

**Issue by dbashford** [dbashford/mimosa#44]
This is ok

```
  paths:
    underscore: 'vendor/underscore'

  shim:
    'underscore':
      deps: []
      exports: '_' 
```

Mimosa currently logs an error for the shim named 'underscore' because it doesn't find an 'underscore'
